# Portfolio netlify.toml
[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Rule to enforce trailing slash for /macro-logger specifically.
# Try this WITHOUT force=true first.
[[redirects]]
  from = "/macro-logger"
  to = "/macro-logger/"
  status = 301
  # force = true # Temporarily removed

# Proxy rule - KEEP force=true here to ensure it overrides Next.js for this path.
[[redirects]]
  from = "/macro-logger/*"
  to = "https://macrologger.netlify.app/macro-logger/:splat"
  status = 200
  force = true
