# In PORTFOLIO's netlify.toml (ibrahimqi.com)

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs" 

# ONLY this rule for /macro-logger for now
[[redirects]]
  from = "/macro-logger/*"
  to = "https://macrologger.netlify.app/macro-logger/:splat"
  status = 200
  force = true 
